### ISSUE TITLE
Where do you find these APIs

### ISSUE THREAD

**Issue by umialpha** [dir/LouisVuittonAPI#5]
Hi, thx for your repo. It is useful. I am wondering how did you find these APIs?

**Comment by XINYI-P** [comment]
Thanks for the sharing! But why it shows that I don't have permission to access the page on this server.

**Comment by dir** [comment]
Hey there @umialpha, you're welcome. I found these APIs using tools like Fiddler and Charles, and also the Google Chrome networking tools. 

I would learn about these concepts in this order:

1. HTML/CSS/JS (don't have to learn how to write them, just what they are and their role in the web) 
2.  HTTP (https://developer.mozilla.org/en-US/docs/Web/HTTP/Overview)
3. Capturing HTTP requests
4. Python
5. Sending HTTP requests in Python

This is simplified, but generally speaking this is about all of the concepts you'd need to understand to write this script here.
