### ISSUE TITLE
The server forbidden the access

### ISSUE THREAD

**Issue by XINYI-P** [dir/LouisVuittonAPI#7]
Thanks for the sharing. Although I know it's a far away long time project, why the page alarms that access denied, you do not have permission to the page on this server when I tried to go to the bag page...

**Comment by dir** [comment]
Thank you for the thanks! 

Unfortunately I haven't worked on this project in years, and it's safe to say Louis Vuitton has changed their eComm system in that timeframe, hence causing the issue you are having. I might give it an update soon, if not I will archive the project.
